# Generated by Django 3.1.6 on 2021-02-06 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('continent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=3)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='continent.continent')),
            ],
        ),
    ]
