# Generated by Django 3.1.6 on 2021-02-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=3)),
                ('continent', models.CharField(choices=[('AF', 'Africa'), ('AS', 'Asia'), ('AN', 'Antartica'), ('EU', 'Europe'), ('NA', 'North America'), ('SA', 'South America')], default='AF', max_length=30)),
            ],
        ),
    ]
