# Generated by Django 3.1.6 on 2021-02-06 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('city_code', models.CharField(max_length=4)),
                ('geo_latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('geo_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citys', to='country.country')),
            ],
        ),
    ]
